[package]
name = "abbrv"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.11", features = ["json"] }
rocket = "0.5.0-rc.2"
serde_json = "1.0.83"

[[bin]]
name = "abbrv"
path = "src/main.rs"

[[bin]]
name = "abbrv_forward"
path = "src/forward.rs"
